// 200 fake notifications. Dealt from a shuffled deck — no repeats in a
// session until the whole deck has been used (see drawNotification).

export const FAKE_NOTIFS = [
  { icon: '📞', title: 'Mum', body: 'Missed call (2)' },
  { icon: '📞', title: 'Mum', body: 'Missed call (7). She knows what you’re doing.' },
  { icon: '📞', title: 'Unknown', body: 'Probably about your car insurance' },
  { icon: '📞', title: 'Dad', body: 'Missed call. He’ll say he never rang.' },
  { icon: '📞', title: 'Nan', body: 'Missed call (1). You monster.' },
  { icon: '📞', title: 'Work', body: 'Missed call. Definitely nothing urgent.' },
  { icon: '📞', title: 'Voicemail', body: 'You have 14 unheard messages from 2019' },
  { icon: '💬', title: 'Dave', body: 'you still holding that button lol' },
  { icon: '💬', title: 'Dave', body: 'mate the football’s started' },
  { icon: '💬', title: 'Dave', body: 'right well I’m off to the pub without you' },
  { icon: '💬', title: 'Sarah', body: 'We need to talk.' },
  { icon: '💬', title: 'Sarah', body: 'Ignore my last message' },
  { icon: '💬', title: 'Group: The Lads', body: '47 new messages' },
  { icon: '💬', title: 'Group: The Lads', body: 'Someone sent a voice note. 4 minutes long.' },
  { icon: '💬', title: 'Group: Family', body: 'Auntie Carol has sent a minion meme' },
  { icon: '💬', title: 'Group: Family', body: 'Mum: who keeps changing the group name' },
  { icon: '💬', title: 'Landlord', body: 'Quick chat when you’re free?' },
  { icon: '💬', title: 'Gaz', body: 'u owe me £4.50 from March' },
  { icon: '💬', title: 'Kelly', body: 'omg have you seen this' },
  { icon: '💬', title: 'Unknown', body: 'Hi, is this still available?' },
  { icon: '💬', title: 'Steve (Gym)', body: 'you coming or what' },
  { icon: '💬', title: 'Jess', body: 'typing…' },
  { icon: '💬', title: 'Tom', body: 'bro. the button. let it go.' },
  { icon: '🔋', title: 'Battery', body: '3% remaining. Probably.' },
  { icon: '🔋', title: 'Battery', body: 'Low power mode enabled. Like your social life.' },
  { icon: '🔋', title: 'Battery', body: 'Your battery is fine. Are you?' },
  { icon: '🔋', title: 'Charger', body: 'Slow charging cable detected. As usual.' },
  { icon: '📰', title: 'Breaking', body: 'Local person still holding button' },
  { icon: '📰', title: 'Breaking', body: 'Area thumb refuses to give up' },
  { icon: '📰', title: 'News', body: 'Scientists confirm buttons don’t care about you' },
  { icon: '📰', title: 'News', body: 'Everything happening as normal without you' },
  { icon: '📰', title: 'News', body: 'Weather: it’s raining. Obviously.' },
  { icon: '📰', title: 'Sport', body: 'Your team conceded. Twice. Just now.' },
  { icon: '📰', title: 'Local News', body: 'Man finds better use of an afternoon' },
  { icon: '📰', title: 'Finance', body: 'The pound did something. Nobody knows what.' },
  { icon: '🫖', title: 'Kettle', body: 'Your brew has gone cold' },
  { icon: '🫖', title: 'Kettle', body: 'Boiled 20 minutes ago. Devastated.' },
  { icon: '🫖', title: 'Kettle', body: 'I’ll boil myself then, shall I' },
  { icon: '☕', title: 'Coffee', body: 'Your flat white is now a flat cold' },
  { icon: '❤️', title: 'New match', body: 'It’s the button. It likes you too.' },
  { icon: '❤️', title: 'New match', body: 'Someone swiped right. They can wait, apparently.' },
  { icon: '❤️', title: 'Dating app', body: 'Your match unmatched. Coincidence?' },
  { icon: '❤️', title: 'Dating app', body: 'Complete your profile: interests — "buttons"?' },
  { icon: '💘', title: 'Dating app', body: 'People near you are outside. Living.' },
  { icon: '📦', title: 'Delivery', body: 'Your parcel is 2 stops away' },
  { icon: '📦', title: 'Delivery', body: 'Driver attempted delivery. He didn’t.' },
  { icon: '📦', title: 'Delivery', body: 'Your parcel is with your neighbour. The weird one.' },
  { icon: '📦', title: 'Delivery', body: 'Left in a safe place: visible from space' },
  { icon: '📦', title: 'Delivery', body: 'Your parcel has been delivered to the wrong house. Again.' },
  { icon: '📦', title: 'Delivery', body: 'Running late. Relatable.' },
  { icon: '🏆', title: 'Achievement', body: 'Tap to claim your prize (do not)' },
  { icon: '🏆', title: 'Achievement', body: 'Nothing unlocked. Keep holding.' },
  { icon: '🏆', title: 'Achievement', body: 'You’ve been nominated for Most Available Person' },
  { icon: '🐕', title: 'Reminder', body: 'The dog wants out' },
  { icon: '🐕', title: 'Reminder', body: 'The dog has given up on you' },
  { icon: '🐈', title: 'Reminder', body: 'The cat has knocked something off. On purpose.' },
  { icon: '🐈', title: 'Cat cam', body: 'Motion detected: judgement' },
  { icon: '🍕', title: 'Takeaway', body: '20% off if you stop this nonsense right now' },
  { icon: '🍕', title: 'Takeaway', body: 'Your usual? You know you want to.' },
  { icon: '🍔', title: 'Takeaway', body: 'Free delivery ends in 10 minutes' },
  { icon: '🥡', title: 'Takeaway', body: 'The Golden Dragon misses you' },
  { icon: '📅', title: 'Calendar', body: 'Meeting in 5 minutes. Ha.' },
  { icon: '📅', title: 'Calendar', body: 'Event: "be somewhere else" — now' },
  { icon: '📅', title: 'Calendar', body: 'Tomorrow: consequences' },
  { icon: '📅', title: 'Calendar', body: 'Reminder: you said you’d start jogging today' },
  { icon: '⏰', title: 'Alarm', body: 'Your 7am alarm is judging you from the past' },
  { icon: '💼', title: 'Work', body: 'Your boss is typing…' },
  { icon: '💼', title: 'Work', body: 'Quick question, no rush (there is rush)' },
  { icon: '💼', title: 'Teams', body: 'You have been added to 3 new channels' },
  { icon: '💼', title: 'Teams', body: 'Meeting started 4 minutes ago. Camera on, please.' },
  { icon: '📧', title: 'Email', body: 'RE: RE: RE: RE: Quick one' },
  { icon: '📧', title: 'Email', body: 'Your inbox has reached 4,000 unread. Congratulations.' },
  { icon: '📧', title: 'Email', body: 'Newsletter you never signed up for: issue 341' },
  { icon: '📧', title: 'Email', body: 'URGENT: not urgent' },
  { icon: '📧', title: 'HR', body: 'Mandatory training due yesterday' },
  { icon: '🏦', title: 'Bank', body: 'You’ve spent £0.00 today. Suspicious.' },
  { icon: '🏦', title: 'Bank', body: 'Direct debit taken: £39.99, "you know the one"' },
  { icon: '🏦', title: 'Bank', body: 'Your balance would like a word' },
  { icon: '🏦', title: 'Bank', body: 'New login from your own phone. Panic anyway.' },
  { icon: '💳', title: 'Card', body: 'Subscription renewed: thing you forgot about' },
  { icon: '📈', title: 'Investments', body: 'Down 4%. Best not to look.' },
  { icon: '🪙', title: 'Crypto', body: 'Your coin did a thing. It’s bad.' },
  { icon: '🏃', title: 'Fitness', body: 'You’ve taken 12 steps today' },
  { icon: '🏃', title: 'Fitness', body: 'Your mate Dave just logged a 10k. Show-off.' },
  { icon: '🏃', title: 'Fitness', body: 'Streak lost. Like your dignity.' },
  { icon: '⌚', title: 'Watch', body: 'Time to stand! Or at least move your thumb. Oh.' },
  { icon: '⌚', title: 'Watch', body: 'Unusual heart rate detected: boredom' },
  { icon: '🧘', title: 'Mindfulness', body: 'Take a deep breath. Keep holding though.' },
  { icon: '🧘', title: 'Mindfulness', body: 'Day 1 of your streak. Again.' },
  { icon: '💧', title: 'Hydration', body: 'You haven’t drunk water since Tuesday' },
  { icon: '😴', title: 'Sleep app', body: 'Bedtime in 8 hours. Plan accordingly.' },
  { icon: '📱', title: 'Screen Time', body: 'Up 340% this week. Well done.' },
  { icon: '📱', title: 'System', body: 'Storage almost full: 9,000 screenshots' },
  { icon: '📱', title: 'System', body: 'Update available. It will change nothing.' },
  { icon: '📱', title: 'System', body: 'Your phone will restart at the worst moment' },
  { icon: '🛜', title: 'Wi-Fi', body: 'Connected to "BT-Hub-42". Barely.' },
  { icon: '🛜', title: 'Wi-Fi', body: 'The router needs turning off and on. You know it.' },
  { icon: '🔒', title: 'Security', body: 'Someone tried your password: it was you' },
  { icon: '🔒', title: 'Security', body: 'Your password expired. All 1 of them.' },
  { icon: '🎵', title: 'Music', body: 'Your playlist ended 20 minutes ago. Silence since.' },
  { icon: '🎵', title: 'Music', body: 'Because you listened to one sad song: 40 more' },
  { icon: '🎧', title: 'Podcast', body: 'New episode: 3 hours 12 minutes. Good luck.' },
  { icon: '📺', title: 'Streaming', body: 'Are you still watching? You’re not even watching.' },
  { icon: '📺', title: 'Streaming', body: 'New series added. You’ll save it and never watch it.' },
  { icon: '📺', title: 'Streaming', body: 'Price increase. Effective immediately. Obviously.' },
  { icon: '🎮', title: 'Games', body: 'Your daily reward expires soon. This is also a game.' },
  { icon: '🎮', title: 'Games', body: 'Someone beat your high score in a better game' },
  { icon: '📸', title: 'Photos', body: 'Memories: you, outdoors, 2021' },
  { icon: '📸', title: 'Photos', body: 'On this day: you were doing something worthwhile' },
  { icon: '🖼️', title: 'Photos', body: 'Storage full of blurry dog pictures' },
  { icon: '👍', title: 'Social', body: 'Someone liked your post from 2018' },
  { icon: '👍', title: 'Social', body: 'Your ex is online' },
  { icon: '👍', title: 'Social', body: '3 people you don’t remember viewed your profile' },
  { icon: '👍', title: 'Social', body: 'Trending: everything except this' },
  { icon: '🐦', title: 'Social', body: 'You wouldn’t believe what’s kicking off. Stay strong.' },
  { icon: '📹', title: 'Social', body: 'Live now: someone doing something with their life' },
  { icon: '🤳', title: 'Social', body: 'Your mate posted a gym selfie. Again.' },
  { icon: '🛒', title: 'Shopping', body: 'Item in your basket dropped 2p' },
  { icon: '🛒', title: 'Shopping', body: 'You left 14 things in your basket. They’re fine.' },
  { icon: '🛒', title: 'Shopping', body: 'Order again? You only bought it yesterday.' },
  { icon: '🏷️', title: 'Deals', body: 'FLASH SALE on things you don’t need' },
  { icon: '🏷️', title: 'Deals', body: 'Limited time offer: unlimited time, actually' },
  { icon: '🚗', title: 'Car', body: 'MOT due. You knew this.' },
  { icon: '🚗', title: 'Parking app', body: 'Your session expires in 5 minutes. Sprint.' },
  { icon: '🚗', title: 'Car', body: 'That noise it makes? Still making it.' },
  { icon: '⛽', title: 'Fuel', body: 'Petrol’s gone up while you’ve been holding' },
  { icon: '🚌', title: 'Transport', body: 'Your bus came early. First time ever.' },
  { icon: '🚆', title: 'Trains', body: 'Delayed. You didn’t even ask.' },
  { icon: '🚆', title: 'Trains', body: 'Rail replacement bus. My condolences.' },
  { icon: '✈️', title: 'Flights', body: 'Prices to Alicante dropped. Just saying.' },
  { icon: '🏠', title: 'Smart home', body: 'Front door: probably fine' },
  { icon: '🏠', title: 'Smart home', body: 'Someone’s at the door. Or a moth. Same alert.' },
  { icon: '🏠', title: 'Doorbell', body: 'Motion detected: next door’s bin' },
  { icon: '💡', title: 'Smart home', body: 'Living room lamp is unreachable. Emotionally.' },
  { icon: '🌡️', title: 'Thermostat', body: 'Heating on. It’s July. Who did this.' },
  { icon: '🧺', title: 'Washing machine', body: 'Cycle finished 3 hours ago. It’s going smelly.' },
  { icon: '🧊', title: 'Fridge', body: 'Door open. For the drama.' },
  { icon: '🤖', title: 'Robot vacuum', body: 'Stuck under the sofa. Send help.' },
  { icon: '🖨️', title: 'Printer', body: 'Out of magenta. You printed in black and white.' },
  { icon: '☁️', title: 'Weather', body: 'Rain starting in 10 minutes. You’re inside. Irrelevant.' },
  { icon: '☁️', title: 'Weather', body: 'UV index: low. Like your chances of stopping.' },
  { icon: '🌧️', title: 'Weather', body: 'Yellow warning for drizzle' },
  { icon: '🌞', title: 'Weather', body: 'Sunniest day of the year. Shame.' },
  { icon: '💨', title: 'Weather', body: 'Wind gusts up to "bins everywhere"' },
  { icon: '❄️', title: 'Weather', body: 'Feels like -2. Feels like letting go, doesn’t it.' },
  { icon: '🧾', title: 'Bills', body: 'Your energy bill is ready. Sit down first.' },
  { icon: '🧾', title: 'Council', body: 'Bin day changed. Chaos imminent.' },
  { icon: '🧾', title: 'Council', body: 'Your bin was not collected. Reason: vibes.' },
  { icon: '📄', title: 'Documents', body: 'Your tax return says hello' },
  { icon: '🩺', title: 'GP', body: 'Appointment available in 6 weeks. Book now or else.' },
  { icon: '🦷', title: 'Dentist', body: 'You’re due a check-up. Since 2022.' },
  { icon: '💊', title: 'Pharmacy', body: 'Prescription ready. Third reminder.' },
  { icon: '👓', title: 'Opticians', body: 'Squinting at this? Thought so.' },
  { icon: '✂️', title: 'Barber', body: 'Your appointment is in 15 minutes. Across town.' },
  { icon: '🎂', title: 'Reminder', body: 'It’s someone’s birthday. You know who. Text them.' },
  { icon: '🎂', title: 'Facebook', body: '3 birthdays today. You’ll ignore all of them.' },
  { icon: '🎁', title: 'Reminder', body: 'Anniversary next week. Start panicking now.' },
  { icon: '📚', title: 'Library', body: 'Book overdue: "Getting Things Done"' },
  { icon: '🦉', title: 'Language app', body: 'The owl has noticed your absence' },
  { icon: '🦉', title: 'Language app', body: 'These reminders don’t seem to be working' },
  { icon: '🦉', title: 'Language app', body: 'Your Spanish streak died. Adiós.' },
  { icon: '♟️', title: 'Chess app', body: 'Your opponent moved 3 days ago. Still your go.' },
  { icon: '🧩', title: 'Puzzle app', body: 'Today’s puzzle: everyone found it easy but you' },
  { icon: '📖', title: 'Reading app', body: 'You’ve read 0 minutes this week. New record.' },
  { icon: '🍎', title: 'Diet app', body: 'You forgot to log lunch. And breakfast. And Tuesday.' },
  { icon: '🍺', title: 'Pub', body: 'Quiz night starts in an hour. Your team needs you.' },
  { icon: '🍺', title: 'The Red Lion', body: 'Your table is ready. Has been for a while.' },
  { icon: '⚽', title: 'Five-a-side', body: 'You’re down to 4. Gary’s "injured" again.' },
  { icon: '🎳', title: 'Bowling', body: 'Booking confirmed for the thing you forgot about' },
  { icon: '🎬', title: 'Cinema', body: 'Your film starts in 20 minutes. Trailers though.' },
  { icon: '🎟️', title: 'Tickets', body: 'Presale ends soon for a band you half like' },
  { icon: '🎫', title: 'Lottery', body: 'You didn’t win. Saved you checking.' },
  { icon: '🔔', title: 'App', body: 'We miss you! — an app you opened once' },
  { icon: '🔔', title: 'App', body: 'Turn on notifications to get more of these' },
  { icon: '🔔', title: 'App', body: 'Rate us! 5 stars means you can stop getting this.' },
  { icon: '🔔', title: 'App', body: 'New features you will never find' },
  { icon: '🔔', title: 'App', body: 'Your free trial ended. The charging has begun.' },
  { icon: '🕹️', title: 'This game', body: 'Hold The Button would like to send you notifications. Too late.' },
  { icon: '🔴', title: 'The Button', body: 'I can feel your grip weakening' },
  { icon: '🔴', title: 'The Button', body: 'Blink twice if you need rescuing' },
  { icon: '🔴', title: 'The Button', body: 'This notification is a distraction. Ignore m— too late?' },
  { icon: '🔴', title: 'The Button', body: 'Your thumb and I are in a relationship now' },
  { icon: '🔴', title: 'The Button', body: 'Other players let go ages ago. Just saying.' },
  { icon: '👻', title: 'Unknown app', body: 'You have 1 new everything' },
  { icon: '🎙️', title: 'Voice assistant', body: 'Sorry, I didn’t catch that. Nobody spoke.' },
  { icon: '🗺️', title: 'Maps', body: 'Traffic is heavy on a road you’re not on' },
  { icon: '🗺️', title: 'Maps', body: 'Rate your visit to: your own house' },
  { icon: '🗺️', title: 'Timeline', body: 'You visited: nowhere. All month.' },
  { icon: '🍀', title: 'Horoscope', body: 'Today: you will hold something for too long' },
  { icon: '🔮', title: 'Horoscope', body: 'Mercury is in retrograde. Blame that.' },
  { icon: '🧠', title: 'Brain app', body: 'Your brain age: don’t worry about it' },
  { icon: '👴', title: 'Ancestry', body: 'Your DNA results: 12% stubborn' },
  { icon: '🪪', title: 'Passport', body: 'Expires sooner than you think' },
  { icon: '🧯', title: 'Smoke alarm', body: 'Low battery. It will chirp at 3am. Once an hour.' },
  { icon: '🪫', title: 'Doorbell cam', body: 'Battery died mid-delivery. Classic.' },
  { icon: '🚨', title: 'Neighbourhood app', body: 'Suspicious man seen "walking"' },
  { icon: '🚨', title: 'Neighbourhood app', body: 'Karen has posted about the bins again' },
  { icon: '🐦‍⬛', title: 'Bird app', body: 'A magpie is in your garden. One for sorrow.' },
  { icon: '🌻', title: 'Plant app', body: 'Your fern is dying. It’s watching you do this.' },
  { icon: '🌻', title: 'Plant app', body: 'Water me. — the cactus, somehow' },
  { icon: '🍞', title: 'Supermarket', body: 'Your usual bread is out of stock. Anarchy.' },
  { icon: '🛍️', title: 'Supermarket', body: 'Clubcard points expiring: 42p worth' },
  { icon: '🧀', title: 'Supermarket', body: 'Cheese is on offer. This is not a drill.' },
  { icon: '🥛', title: 'Reminder', body: 'The milk went off. You smelled it. You used it anyway.' },
  { icon: '♻️', title: 'Reminder', body: 'It’s recycling week. Or is it? Nobody knows.' },
  { icon: '🧹', title: 'Reminder', body: 'The big clean you planned: still pending' },
  { icon: '🛏️', title: 'Reminder', body: 'Bed sheets. It’s been a while. You know it has.' },
]

// Shuffled-deck dealer: every notification appears once before any repeats.
let deck = []

function shuffle(arr) {
  const a = arr.slice()
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

export function drawNotification() {
  if (deck.length === 0) deck = shuffle(FAKE_NOTIFS)
  return deck.pop()
}
